language: objective-c

os: 
- osx

before_install:
# Get build dependencies
- brew install cmake
- brew install wget
- LIBDIR=~/Library/Frameworks/
- wget https://www.libsdl.org/release/SDL2-2.0.3.dmg
- wget http://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.dmg
- hdiutil mount SDL2_mixer-2.0.0.dmg
- hdiutil mount SDL2-2.0.3.dmg
- mkdir -p $LIBDIR
- cp -r /Volumes/SDL2/SDL2.framework $LIBDIR
- cp -r /Volumes/SDL2_mixer/SDL2_mixer.framework $LIBDIR

install:
- cd $TRAVIS_BUILD_DIR
# Create unix makefiles
- cmake -DCMAKE_BUILD_TYPE=Release

before_script:
# Don't ask for confirmation when using scp
- echo -e "Host frs.sourceforge.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
# Build CaesarIA
- make
after_success:
- cd $TRAVIS_BUILD_DIR/../caesaria-test
# Prepare ZIP archive
- ZIPNAME=caesaria-0.4-linux-$TRAVIS_BRANCH-`date +"%Y%m%d"`.zip
- echo Compress to $ZIPNAME
- zip -r $ZIPNAME *
- chmod 666 $ZIPNAME
# Upload to server
- sshpass -p "$SCP_PASS" scp -v $ZIPNAME dalerank@frs.sourceforge.net:/home/frs/project/opencaesar3/bin/
env:
