language: cpp

compiler:
- gcc

branches:
  - windows-build

before_install:
# Get build dependencies
- sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots #libsdl2
- sudo apt-get -qq update
- sudo apt-get -qq install cmake p7zip-full build-essential 
- sudo apt-get -qq install binutils-mingw-w64-i686  
- sudo apt-get -qq install gcc-mingw-w64-i686
- sudo apt-get -qq install g++-mingw-w64-i686
- sudo apt-get -qq install sshpass
# Get SDL
- wget https://www.libsdl.org/release/SDL2-devel-2.0.3-mingw.tar.gz
- tar xfz SDL2-devel-2.0.3-mingw.tar.gz
- sudo cp SDL2-2.0.3/lib/x86/* /usr/i686-w64-mingw32/lib/
- sudo cp -r SDL2-2.0.3/i686-w64-mingw32/include/* /usr/i686-w64-mingw32/include/
- sudo cp -r SDL2-2.0.3/i686-w64-mingw32/lib/* /usr/i686-w64-mingw32/lib/
#- sudo chmod +x /usr/i586-mingw32msvc/bin/sdl-config
# fix winapifamily.h
- wget https://www.dropbox.com/s/dm5lto9qlyfc418/SDL_platform.h
- sudo cp SDL_platform.h /usr/i686-w64-mingw32/include/SDL2
# Get SDL Mixer		
- wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.0-mingw.tar.gz
- tar xfz SDL2_mixer-devel-2.0.0-mingw.tar.gz
- sudo cp -r SDL2_mixer-2.0.0/i686-w64-mingw32/include/* /usr/i686-w64-mingw32/include/
- sudo cp -r SDL2_mixer-2.0.0/i686-w64-mingw32/lib/*.a /usr/i686-w64-mingw32/lib/
- sudo cp -r SDL2_mixer-2.0.0/i686-w64-mingw32/bin/*.dll /usr/i686-w64-mingw32/lib/
install:
- cd $TRAVIS_BUILD_DIR
# Create unix makefiles
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=xcompile/win32-cross.cmake
before_script:

script:
# Build CaesarIA
- make
after_success:
- export REVISION_NUMBER=`git rev-list HEAD --count`
- cd $TRAVIS_BUILD_DIR/../caesaria-test
# Prepare ZIP archive
- ZIPNAME=caesaria-0.4-$TRAVIS_BRANCH-`date +"%Y%m%d"`.zip
- echo Compress to $ZIPNAME
- zip -r $ZIPNAME *
- chmod 666 $ZIPNAME
# Upload to server
- sshpass -p "$SCP_PASS" scp -v $ZIPNAME dalerank@frs.sourceforge.net:/home/frs/project/opencaesar3/bin/
env:
