language: cpp

compiler:
- clang
- gcc

before_install:
# Get build dependencies
- sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots #libsdl2
- sudo dpkg --add-architecture i386
- sudo apt-get -qq update
- sudi apt-get -qq install ia32-libs
- sudo apt-get -qq install cmake build-essential libsdl2-dev libsdl2-mixer-dev
- sudo apt-get -qq install gcc-multilib g++-multilib

install:
- cd $TRAVIS_BUILD_DIR
- mkdir ../caeasaria-test
# Create unix makefiles
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=xcompile/linux32.cmake

script:
# Build CaesarIA
- make

