language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install -qq libsdl1.2-dev
  - sudo apt-get install -qq libsdl-mixer1.2-dev


before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script: make
