language: cpp

compiler:
- clang
- gcc

branches:
  only:
    - master
    - windows-build

before_install:
# Get build dependencies
- sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots #libsdl2
- sudo apt-get -qq update
- sudo apt-get -qq install cmake build-essential libsdl2-dev libsdl2-mixer-dev

install:
- cd $TRAVIS_BUILD_DIR
# Create unix makefiles
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=xcompile/linux32.cmake

script:
# Build CaesarIA
- make

