language: android

android:
  components:
    - build-tools-19.1.0
    - android-19

before_install:
# ???

before_script:
# Don't ask for confirmation when using scp
- echo -e "Host frs.sourceforge.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
# Build CaesarIA
- cd android
- make DEBUG=0

after_success:
- cd $TRAVIS_BUILD_DIR/android/android-project/bin
- ls
# Prepare ZIP archive
- APKNAME=caesaria-0.4-$TRAVIS_BRANCH-`date +"%Y%m%d"`.apk
- mv CaesarIA-release.apk $APKNAME
# Upload to server
- sshpass -p "$SCP_PASS" scp -v $APKNAME dalerank@frs.sourceforge.net:/home/frs/project/opencaesar3/bin/
